name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 1.9.3
homepage: https://github.com/localizely/intl_utils

publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: '>=2.0.0'
  archive: ^3.1.2
  intl_translation: 
    git:
      url: https://github.com/wisnuwiry/intl_translation.git
      ref: master
  http: ^0.13.0
  path: ^1.8.0
  petitparser: ^4.0.2
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  mockito: ^5.0.0
